spring:
  datasource:
    url: jdbc:h2:mem:tododb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

jwt:
  secret: your-256-bit-secret-key-here
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    com.example.todoapi: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO 